### ISSUE TITLE
Это очень странно

### ISSUE THREAD

**Issue by grechkin-pogrebnyakov** [go-park-mail-ru/2018_2_codeloft#19]
https://github.com/go-park-mail-ru/2018_2_codeloft/blob/b096c6219b488bf5c7a290a8d6193bb9e27804cd/database/database.go#L129

зачем вам делать работу, результат которой почти никогда не понадобится?
В зависимости от ожидаемой нагрузки, сортировать нужно либо при вставке (если очень мало записей в базу и много чтений), либо при отдаче данных (если наоборот, мало чтений, но много записей)

**Comment by Malefaro** [comment]
Здесь сортируется список лидеров. Сортировать при вставке не вариант, так как если не будет регистраций новых пользователей то список лидеров будет один и тот же. 
Если выполнять сортировку каждый раз когда изменяются очки какого либо пользователя, база будет слишком загружена бесконечными сортировками.
Если же сортировать перед отдачей данных, то каждый раз когда какой либо пользователь зайдет проверить список лидеров это будет вызывать сортировку и если захотеть то один пользователь сможет загрузить базу. 
Поэтому был выбран вариант сортировать раз в какой-то промежуток времени(например раз в день)
