### ISSUE TITLE
Возвращать 405, если пришел неверный метод

### ISSUE THREAD

**Issue by vladpereskokov** [go-park-mail-ru/2018_2_codeloft#31]
Сейчас (в каком-то окружении) можно получать пользователей вообще по всем методам. Оставить GET, остальное отбрасывать. 

Разобраться, актуальна ли данная таска или это была проблема с окружением вашим

**Comment by Malefaro** [comment]
Проблема была в том что по какой-то причине по http://codeloft.... была одна версия(старая)
А по https:// другая
